// General Waste
// examples from http://www.netwaste.org.au/recycle-it/what-can-be-recycled/
const Recycleable = {
  red: [
    //"coffee cup",
    "plastic bag", // find words
    "soft plastic", // find words
    "nappies", // find words
    "polystyrene", // find words
    "syringes", // find words
    "medical equipment",
    "medical",
    "hypodermic needle",
    "medical waste", // find words
    "dead animals",
    "oils", // find examples
    "oil",
    "olive oil",
    "cooking oil",
    "vegetable oil",
    "ceramics",
    "earthenware",
    "porcelain",
    "serveware",
    "drinkware",
    "ovenware",
    "lightbulbs",
    "tissue",
    "napkin",
    "paper product",
    "construction paper",
    "serviette",
    "waste",
  ],
  yellow: [
    "paper",
    "newspaper",
    "magazine",
    "catalog",
    "map",
    "phonebook",
    "mail",
    "paperboard",
    "box",
    "card",
    "folder",
    "can",
    "straw",
    "carton",
    "book",
    "cup",
    "envelope",
    "cardboard",
    "vase",
    "plastic",
    "boxboard",
    "box",
    "metal",
    "tin",
    "aluminum",
    "dish",
    "plate",
    "tray",
    "cookware",
    "copper",
    "jewelry",
    "key",
    "steel",
    "pot",
    "bucket",
    "pan",
    "tin",
    "pyrex",
    "utensil",
    "glass",
    "bottle",
    "jar",
    "cup",
    "jug",
    "metal",
    "spoon",
    "fork",
    "office paper",
    "blind",
    "curtain",
    "kitchen utensil",
    "glove",
    "barware",
    "coffee cup sleeve",
    "plastic bottle",

  ],
  green: [ 
    "fruit",
    "vegetable",
    "apple",
    "pear",
    "banana",
    "cucumber",
    "strawberry",
    "apricots",
    "avocado",
    "blackberry",
    "cherry",
    "coconut",
    "date",
    "durian",
    "dragonfruit",
    "grape",
    "grapefruit",
    "kiwi",
    "lime",
    "lemon",
    "lychee",
    "mango",
    "melon",
    "nectarine",
    "olive",
    "orange",
    "peach",
    "pineapple",
    "plum",
    "pomegranate",
    "pomelo",
    "raspberries",
    "watermelon",
    "broccoflower",
    "broccoli",
    "cabbage",
    "celery",
    "corn",
    "basil",
    "rosemary",
    "sage",
    "thyme",
    "kale",
    "lettuce",
    "mushroom",
    "onion",
    "pepper",
    "ginger",
    "wasabi",
    "squash",
    "tomato",
    "potato",
    "hair",
    "wood",
    "popcorn",
    "leaves",
    "egg",
    "pasta",
    "fish",
    "beef",
    "chicken",
    "pork",
    "meat",
    "soy",
    "pumpkin",
    "nut",
    "cheese",
    "toothpicks",
    "pickles",
    "feather",
    "fur",
    "bone",
  ],
  blue: [
    "paper",
    "newspaper",
    "magazine",
    "catalog",
    "map",
    "phonebook",
    "mail",
    "paperboard",
    "cardboard",
    "office paper",
    "paper product",
    "notebook",
    "carton"
  ],
  special: [
    "battery",
    "computer",
    "electronics",
    "bulb",
    "microfilm",
    "cell phone",
    "phone",
    "mobile phone",
    "equipment",
    "inkjet",
    "cartridge",
    "inkjet cardridge",
    "cd",
    "disk",
    "tire",
    "ink cartridge",
    "tv",
    "power cord",
    "personal computer",
    "laptop",
    "portable computer",
  ]

};

module.exports = Recycleable;
