// General Waste
// examples from http://www.netwaste.org.au/recycle-it/what-can-be-recycled/
const Recycleable = {
  red: [
    "coffee cup",
    "plastic bag", // find words
    "soft plastic", // find words
    "nappies", // find words
    "polystyrene", // find words
    "syringes", // find words
    "medical equipment",
    "medical",
    "hypodermic needle",
    "medical waste", // find words
    "dead animals",
    "oils", // find examples
    "oil",
    "olive oil",
    "cooking oil",
    "vegetable oil",
    "ceramics",
    "earthenware",
    "porcelain",
    "serveware",
    "drinkware",
    "ovenware",
    "lightbulbs",
    "tissue",
    "napkin",
    "construction paper",
    "serviette",
    'food',
    'dessert',
    "pasta",
    "fish",
    "beef",
    "chicken",
    "pork",
    "meat",
    "cheese",
    "bone",
    'local food',
    'sports equipment',
    'ball',
    'valencia orange',
    'à la carte food',
    'ice cream',
    'footwear',
    'boot',
    'ingredient',
    'waste container',
    'leather',
    'shoe',
    'pen',
    'snack',
    'junk food',
    'bag',
    'luggage and bags',
    'backpack',
    'jacket',
    'jeans',
    'trousers',
    'outerwear',
    'chorizo',
    'spare ribs',
    'cup',
  ],
  yellow: [ 
    'beverage can',
    'glass bottle',
    'tin can',
    'box',
    'card',
    'folder',
    'can',
    'straw',
    'book',
    'envelope',
    'vase',
    'plastic',
    'boxboard',
    'box',
    'metal',
    'tin',
    'aluminum',
    'dish',
    'plate',
    'tray',
    'cookware',
    'copper',
    'jewelry',
    'key',
    'steel',
    'pot',
    'bucket',
    'pan',
    'tin',
    'pyrex',
    'utensil',
    'glass',
    'bottle',
    'jar',
    'jug',
    'metal',
    'spoon',
    'fork',
    'tableware',
    'blind',
    'curtain',
    'beer bottle',
    'beer',
    'tableware',
    'spray',
    'glasses',
    'distilled beverage',
    'plastic bottle',
    'old fashioned glass',
    'pint glass',
    'highball glass',
    'wheat beer',
    'aluminum can',
    'soft drink',
],
  green: [ 
    "fruit",
    "vegetable",
    "apple",
    "pear",
    "banana",
    "cucumber",
    "strawberry",
    "apricots",
    "avocado",
    "blackberry",
    "cherry",
    "coconut",
    "date",
    "durian",
    "dragonfruit",
    "grape",
    "grapefruit",
    "kiwi",
    "lime",
    "lemon",
    "lychee",
    "mango",
    "melon",
    "nectarine",
    "olive",
    "orange",
    "peach",
    "pineapple",
    "plum",
    "pomegranate",
    "pomelo",
    "raspberries",
    "watermelon",
    "broccoflower",
    "broccoli",
    "cabbage",
    "celery",
    "corn",
    "basil",
    "rosemary",
    "sage",
    "thyme",
    "kale",
    "lettuce",
    "mushroom",
    "onion",
    "pepper",
    "ginger",
    "wasabi",
    "squash",
    "tomato",
    "potato",
    "popcorn",
    "leaves",
    "egg",
    "soy",
    "pumpkin",
    "nut",
    "toothpicks",
    "pickles",
    "feather",
    "fur",
    'vegetarian food',
    'plant',
    'citrus',
    'meyer lemon',
    'banana family',
    'potato chip'
  ],
  blue: [
    "paper",
    "newspaper",
    "magazine",
    "catalog",
    "map",
    "phonebook",
    "mail",
    "paperboard",
    "cardboard",
    "office paper",
    "paper product",
    "notebook",
    "carton"
  ],
  special: [
    'watch',
    "battery",
    "computer",
    "electronics",
    "bulb",
    "microfilm",
    "cell phone",
    "phone",
    "mobile phone",
    "equipment",
    "inkjet",
    "cartridge",
    "inkjet cardridge",
    "cd",
    "disk",
    "tire",
    "tyre",
    "ink cartridge",
    "tv",
    "power cord",
    "personal computer",
    "laptop",
    "portable computer",
    "electronic device",
    "gadget",
    "technology",
    'smartphone',
    'portable communications device',
    'audio equipment',
    'headphones',
    'electronics accessory',
    'e-book readers',
    'mobile device',
    'headset',
    'analog watch'
  ]

};

module.exports = Recycleable;
